name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "✅ Skipping tests for now (add pytest later)"

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_TAG=latest
          COMMIT_TAG=${GITHUB_SHA::8}  # Short SHA for versioning
          ECR_URI=412622496898.dkr.ecr.us-east-1.amazonaws.com/mlops-house-price
          echo "Building image: $ECR_URI:$IMAGE_TAG and $ECR_URI:$COMMIT_TAG"

          # Build Docker image
          docker build -t $ECR_URI:$IMAGE_TAG -t $ECR_URI:$COMMIT_TAG .

          # Optional: Run quick container test
          docker run --rm $ECR_URI:$COMMIT_TAG python --version

          # Push both tags to ECR
          docker push $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:$COMMIT_TAG
